site_name: 'CiviCRM Training Guide'
site_url: https://docs.civicrm.org/training/en/stable/
repo_url: https://github.com/civicrm/civicrm-training-guide
site_description: 'This guide is aimed at CiviCRM trainers who train users, system administrators and developers who would like to learn more about configuring and using CiviCRM'
site_author: 'The CiviCRM community'
theme: material
markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

pages:
- Home: 'index.md'
- Sessions:
    - 'Accounting Integration': 'sessions/accounting-integration.md'
    - 'Activities': 'sessions/activities.md'
    - 'Campaigns, Surveys and Petitions': 'sessions/campaigns-surveys-and-petitions.md'
    - 'Case Management': 'sessions/case-management.md'
    - 'Communications': 'sessions/communications.md'
    - 'Contribute': 'sessions/contribute.md'
    - 'Duplicates': 'sessions/duplicates.md'
    - 'Events': 'sessions/events.md'
    - 'Grant': 'sessions/grant.md'
    - 'Introduction to CiviCRM': 'sessions/introduction-civicrm.md'
    - 'Introduction to the training': 'sessions/introduction-training.md'
    - 'Organising Data': 'sessions/organising-data.md'
    - 'Profiles': 'sessions/profiles.md'
    - 'Reports': 'sessions/reports.md'
    - 'Searches': 'sessions/searches.md'
    - 'Set up': 'sessions/set-up.md'
    - 'Website Integration': 'sessions/website-integration.md'
- Courses:
    - 'Learn how to administer CiviCRM software in 1 day': 'sessions/admin-1-day.md'
    - 'Learn how to administer CiviCRM software in 2 days': 'sessions/admin-2-days.md'
    - 'CiviCRM for Fundraisers in 1 day': 'fundraising-1-day.md'
    
    
    
        
    

