site_name: 'CiviCRM user and admin training: trainers guide'

#site_url: https://docs.civicrm.org/training/en/stable/
repo_url: https://github.com/civicrm/civicrm-training-guide

site_description: 'This guide is aimed at CiviCRM trainers who train users, system administrators and developers who would like to learn more about configuring and using CiviCRM'

site_author: 'The CiviCRM community'
theme: material

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

nav:
  - Home: index.md
  - Courses:
    - 2 day instensive training: 2-day-course.md
  - Sessions:
    - Introduction:
      - Session: introduction.md
      - Handout: handout/introduction.md
    - Introduction to CiviCRM:
      - Session: introduction-to-civicrm.md
      - Handout: handout/introduction-to-civicrm.md
    - Setup:
      - Session: setup.md
      - Handout: handout/setup.md
    - Organising data:
      - Session: organising-data.md
      - Handout: handout/organising-data.md
    - Profiles:
      - Session: profiles.md
      - Handout: handout/profiles.md
    - Contribute:
      - Session: contribute.md
      - Handout: handout/contribute.md
    - Duplicates:
      - Session: duplicates.md
      - Handout: handout/duplicates.md
    - Website integration:
      - Session: website-integration.md
      - Handout: handout/website-integration.md
    - Events:
      - Session: events.md
      - Handout: handout/events.md
    - Membership:
      - Session: membership.md
      - Handout: handout/membership.md
    - Communications:
      - Sessions: communications.md
      - Handout: handout/communications.md
    - Reports:
      - Session: reports.md
      - Handout: handout/reports.md
    - Case management:
      - Session: case.md
      - Handout: handout/case.md
    - Grant:
      - Session: grants.md
      - Handout: handout/grants.md
    - Campaign:
      - Session: campaign.md
      - Handout: handout/campaign.md

dev_host: 0.0.0.0:8000
